mip:
  enable: true
  cssmin: true
  exclude:
    - '/mippath.html'
    - 'https://www.mipengine.org/validator/preview'
    - 'https://www.mipengine.org/validator/validate'
    - 'https://www.mipengine.org/platform'
